# Generated by Django 5.1.6 on 2025-02-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike')], max_length=100)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='previewimages')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('km_drive', models.IntegerField()),
                ('ownership', models.CharField(blank=True, choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], max_length=100, null=True)),
                ('car_type', models.CharField(blank=True, choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback')], max_length=100, null=True)),
                ('bike_type', models.CharField(blank=True, choices=[('Cruiser', 'Cruiser'), ('Sports', 'Sports'), ('Commuter', 'Commuter')], max_length=100, null=True)),
            ],
        ),
    ]
